<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>
    <groupId>com.github.orcas</groupId>
    <artifactId>workflow-orchestrator</artifactId>
    <version>0.4.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>workflow-orchestrator-core</module>
        <module>workflow-orchestrator-spring-boot-starter</module>
        <module>workflow-orchestrator-service-starter</module>
        <module>example-app</module>
    </modules>
    <properties>
        <java.version>25</java.version>
        <maven.compiler.release>25</maven.compiler.release>
        <testcontainers.version>2.0.5</testcontainers.version>
        <rest-assured.version>6.0.1</rest-assured.version>
        <awaitility.version>4.3.0</awaitility.version>
        <resilience4j.version>2.4.0</resilience4j.version>
        <wiremock.image>wiremock/wiremock:3.13.2</wiremock.image>
    </properties>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.14.1</version>
                    <configuration>
                        <release>25</release>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.4</version>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>4.1.1</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
