<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" version="1.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.orcas</groupId>
        <artifactId>workflow-orchestrator-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>workflow-orchestrator-spring-boot-starter</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.github.orcas</groupId>
            <artifactId>workflow-orchestrator-jdbc-autoconfigure</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.orcas</groupId>
            <artifactId>workflow-orchestrator-kafka-autoconfigure</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.orcas</groupId>
            <artifactId>workflow-orchestrator-dashboard-service-autoconfigure</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
